pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - approved-reviews-by=Snazzah
    actions:
      merge:
        method: merge
  - name: Merge non-breaking dependencies automatically
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - title~=from (?P<major>\d+).\d+.\d+ to (?P=major).\d+.\d+
    actions:
      merge:
        method: merge
  - name: Notify breaking dependencies automatically
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - title~=from (?P<major>\d+).\d+.\d+ to (?!(?P=major).\d+.\d+)
    actions:
      comment:
        message: |
          This PR features a major change and requires further approval.
      request_reviews:
        users:
          - Snazzah
